version: '3'
services:
    web:
        image: "nginx:latest"
        ports:
            - "8080:80"
        volumes:
            - ./src:/src
            - ./environment/default.conf:/etc/nginx/conf.d/default.conf
            - ./environment/nginx/logs:/var/log/nginx/

    php-fpm:
        build: 
            context: ./environment
            dockerfile: PHP_Dockerfile
        volumes:
            - ./src:/src
        entrypoint: ./init.sh

    database:
        image: "mongo:latest"